import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "./src/context/useAuthContext";
import { ProfileProvider } from "./src/context/userProfileContext";
import { Toaster } from "sonner";
import "swiper/swiper.css";

import { SearchPostProvider } from "./src/context/usePostContext";
import { AuthGate } from "./src/components/GateAuth/AuthGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reno",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster richColors position="top-right" />
        <AuthProvider>
          {/* <AuthGate> */}
            <ProfileProvider>
              <SearchPostProvider>
                {children}
              </SearchPostProvider>
          </ProfileProvider>
          {/* </AuthGate> */}
        </AuthProvider>
      </body>
    </html>
  );
}
